# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='opsticket.Ticket', verbose_name='所属工单'),
        ),
    ]
