# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsticket', '0002_auto_20191126_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expired_time',
            field=models.DateTimeField(blank=True, verbose_name='工单销毁时间'),
        ),
    ]
