# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsticket', '0003_auto_20191127_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.CharField(max_length=128, verbose_name='指派对象'),
        ),
    ]
