# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsticket', '0004_auto_20191129_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'permissions': (('visit_Ticket', 'Can visit Ticket'),), 'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
    ]
